kumuluzee:
  datasources:
    - jndi-name: jdbc/FishsDS
      connection-url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-name: org.h2.Driver
      username: sa
      password:
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/FishsDS
      disk-space-health-check:
        type: liveness
        threshold: 1000