apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishs-application
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishs-application
  template:
    metadata:
      labels:
        app: fishs-application
    spec:
      containers:
        - name: fishs-application
          image: keywer/microprofile/k3s-application:v1.0.0
          envFrom:
            - configMapRef:
                name: k3s-fishs-config
            - secretRef:
                name: k3s-fishs-secret
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: fishs-application
  namespace: default
spec:
  selector:
    app: fishs-application
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer