apiVersion: v1
kind: Pod
metadata:
  name: fishs-application
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fishs-application
  template:
    metadata:
      labels:
        app: fishs-application
    spec:
      containers:
        - name: fishs-application
          image: keywer/microprofile/k3s-fishs:v1.0.0
          envFrom:
            - configMapRef:
                name: k3s-fishs-config
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: fishs-application
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fish
