apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishs-application
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishs-application
  template:
    metadata:
      labels:
        app: fishs-application
    spec:
      containers:
        - name: fishs-application
          image: keywer/microprofile/k3s-application:v1.0.0
          envFrom:
            - configMapRef:
                name: k3s-fishs-config
            - secretRef:
                name: k3s-fishs-secret
          # system probes
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 64Mi
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: fishs-application
  namespace: default
spec:
  selector:
    app: fishs-application
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer