apiVersion: apps/v1
kind: Deployment
metadata:
  name: fish-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fish
  template:
    metadata:
      labels:
        app: fish
    spec:
      containers:
        - image: keywer/microprofile/k3s-fishs:v1.0.0
          name: k3s-fishs
          envFrom:
            - configMapRef:
                name: k3s-fish-config
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: fish
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fish
