apiVersion: v1
kind: Pod
metadata:
  name: fish-database
  namespace: default
spec:
  initContainers:
    - name: fetch
      image: keywer/microprofile/k3s-init-database:v1.0.0
      volumeMounts:
        - mountPath: /database
          name: dump
  containers:
    - name: fish-database
      image: keywer/microprofile/k3s-database:v1.0.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: dump
          mountPath: /database
      ports:
        - containerPort: 1521
  volumes:
    - emptyDir: {}
      name: dump
