apiVersion: v1
kind: Pod
metadata:
  name: fish-database
  namespace: default
spec:
  initContainers:
    - name: init-database
      image: keywer/microprofile/k3s-init-database:v1.0.0
      volumeMounts:
        - name: database
          mountPath: /database
  containers:
    - name: fish-database
      image: keywer/microprofile/k3s-database:v1.0.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: database
          mountPath: /database
      ports:
        - containerPort: 1521
        - containerPort: 8082
  volumes:
    - emptyDir: {}
      name: database
