apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishs-database
  namespace: default
spec:
  selector:
    matchLabels:
      app: fishs-database
  template:
    metadata:
      labels:
        app: fishs-database
    spec:
      initContainers:
        - name: init-database
          image: keywer/microprofile/k3s-init-database:v1.0.0
          command: ['sh', '-c', '/tmp/createDatabase.sh']
          volumeMounts:
            - name: database
              mountPath: /database
      containers:
        - name: fishs-database
          image: keywer/microprofile/k3s-database:v1.0.0
          volumeMounts:
            - name: database
              mountPath: /database
          ports:
            - containerPort: 1521
      volumes:
        - emptyDir: {}
          name: database

---

apiVersion: v1
kind: Service
metadata:
  name: fishs-database
  namespace: default
spec:
  selector:
    app: fishs-database
  ports:
    - port: 1521
      targetPort: 1521
    - port: 8082
      targetPort: 8082