apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  initContainers:
    - name: fetch
      image: keywer/k3s-init-database-fishs:v1.0.0
      command: ["./initdb.sh"]
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: dump
  containers:
    - name: volume-test
      image: keywer/k3s-database-fishs:v1.0.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: dump
          mountPath: /docker-entrypoint-initdb.d
      ports:
        - containerPort: 8082
  volumes:
    - emptyDir: {}
      name: dump
